---

clusters: 

  - name: openstack-services-configure
    vars: !include vars/default.yml
    hosts: !include hosts/all.yml
    images: images/region1/

    services: |

      - name: keystone-configure
        image: 'shaddock/keystone:{{ img_tag }}'
        priority: 30
        volumes:
          - '{{ venv_exec_path }}/keystone:{{ venv_exec_path }}/keystone:rw'
          - '{{ venv_build_path }}:{{ venv_build_path }}:rw'
          - /opt/openstack/etc/keystone:/etc/keystone:rw
          - /var/log/shdk/keystone:/var/log/keystone:rw
        depends-on:
          - {name: mysql, port: 3306}
        environment:
          MYSQL_VIP: '{{ mysql_vip }}'
          MYSQL_USER: '{{ mysql_user }}'
          MYSQL_PASS: '{{ mysql_pass }}'
          KEYSTONE_VIP: '{{ keystone_vip }}'
          KEYSTONE_DB_PASS: '{{ keystone_db_pass }}'
          ADMIN_PASS: '{{ admin_pass }}'
          PATH: '/usr/bin:/bin:{{ venv_exec_path }}/keystone/bin'
        command: 'run.sh'

      - name: glance-configure
        image: 'shaddock/glance:{{ img_tag }}'
        priority: 40
        volumes:
          - '{{ venv_build_path }}:{{ venv_build_path }}:ro'
          - '{{ venv_exec_path }}/glance:{{ venv_exec_path }}/glance:rw'
          - '{{ venv_exec_path }}/python-openstackclient:{{ venv_exec_path }}/python-openstackclient:ro'
          - /opt/openstack/etc/glance:/etc/glance:rw
          - /opt/openstack/osrc:/opt/openstack/osrc:ro
        depends-on:
          - {name: mysql, port: 3306}
          - {name: keystone-public, port: 5000, get: '/v3'}
          - {name: keystone-admin, port: 35357, get: '/v3'}
        environment:
          MYSQL_VIP: '{{ mysql_vip }}'
          MYSQL_USER: '{{ mysql_user }}'
          MYSQL_PASS: '{{ mysql_pass }}'
          KEYSTONE_VIP: '{{ keystone_vip }}'
          GLANCE_VIP: '{{ glance_vip }}'
          GLANCE_DB_PASS: '{{ glance_db_pass }}'
          GLANCE_PASS: '{{ glance_pass }}'
          MEMCACHED_VIP: '{{ memcached_vip }}'
          PATH: '/usr/bin:/bin:{{ venv_exec_path }}/glance/bin:{{ openstackclient_path }}'
          VIRTUAL_ENV: '{{ venv_exec_path }}/glance/'

      - name: nova-configure
        image: 'shaddock/nova:{{ img_tag }}'
        priority: 45
        privileged: True
        volumes:
          - '{{ venv_build_path }}:{{ venv_build_path }}:rw'
          - '{{ venv_exec_path }}/nova:{{ venv_exec_path }}/nova:rw'
          - '{{ venv_exec_path }}/python-openstackclient:{{ venv_exec_path }}/python-openstackclient:ro'
          - /opt/openstack/etc/nova:/etc/nova:rw
          - /opt/openstack/osrc:/opt/openstack/osrc:rw
          - /var/log/shaddock/nova:/var/log/nova:rw
        depends-on:
          - {name: mysql, port: 3306}
          - {name: rabbitmq, port: 5672}
          - {name: keystone-public, port: 5000, get: '/v3'}
          - {name: keystone-admin, port: 35357, get: '/v3'}
        environment:
          RABBIT_USER: '{{ rabbit_user }}'
          RABBIT_PASS: '{{ rabbit_pass }}'
          RABBIT_VIP: '{{ nova_vip }}'
          NOVA_DB_PASS: '{{ nova_db_pass }}'
          MYSQL_VIP: '{{ mysql_vip }}'
          MYSQL_USER: '{{ mysql_user }}'
          MYSQL_PASS: '{{ mysql_pass }}'
          KEYSTONE_VIP: '{{ keystone_vip }}'
          MEMCACHED_VIP: '{{ memcached_vip }}'
          NOVA_PASS: '{{ nova_pass }}'
          NOVA_VIP: '{{ nova_vip }}'
          GLANCE_VIP: '{{ glance_vip }}'
          NEUTRON_VIP: '{{ neutron_vip }}'
          PATH: '/usr/bin:/bin:{{ venv_exec_path }}/nova/bin:{{ openstackclient_path }}'
          VIRTUAL_ENV: '{{ venv_exec_path }}/nova/'
