
---
def_password: 'iAehwS04lHJg5LBs'
admin_password: '5gP6famJjcI48X2O'
mysql_password: '6Iv0e2VGOj9_El6M'

mysql_admin_user: 'admin'

public_vip: '172.17.0.1'
internal_vip: '172.17.0.1'
mysql_vip: '172.17.0.1'

keystone_api_ip: '172.17.0.1'
glance_api_ip: '172.17.0.1'
