
---
def_password: 'iAehwS04lHJg5LBs'
admin_password: '5gP6famJjcI48X2O'
mysql_password: '6Iv0e2VGOj9_El6M'
mysql_admin_user: 'root'
public_vip: '91.121.67.143'
internal_vip: '91.121.67.143'
mysql_vip: '91.121.67.143'
